### PR TITLE
Bugfix and Enhancement type support.  Fixed security-type advisory severities.

### PR DESCRIPTION
**Pull request by Dan0maN**
Enabled support for bugfix and enhancement type updates.  Added severity element into the security advisory types.

### CODE REVIEW

**Comment by Dan0maN** [comment]
Not sure why the bugfix and enhancement advisory types were being ignored, but I re-enabled them and they're working.  At least for Cent7.  Also, the security advisories should print the severity element into them so that you can filter based on severity.

**Comment by kostecky** [comment]
They were originally ignored, since they were not a part of the scope of the project to ensure that critical security vulnerabilities were patched. Non-security related bug fixes and enhancements don't lead to compromised systems.

**Comment by Dan0maN** [comment]
Is there anything else you'd like to see on this?  I could also enhance this to include this as optional if you decide to pull in request #7 from @filirom1.  Please let me know what I can help with.

**Comment by kostecky** [comment]
@Dan0maN If this is made optional with a default to only do security related issues, I can merge it.

**Comment by Dan0maN** [comment]
Okay.  I'll go ahead and re-submit a new PR when finished.

**Pull request closed without merging**
